"""
HTML reporter — generates a self-contained HTML vulnerability report.
"""

from __future__ import annotations

import json
import os
from datetime import datetime
from typing import Any, Dict, List

from scanner.models.vulnerability import Severity, VulnerabilityReport

# Severity colors
_COLORS: Dict[str, str] = {
    "CRITICAL": "#dc3545",
    "HIGH": "#fd7e14",
    "MEDIUM": "#ffc107",
    "LOW": "#0d6efd",
    "INFO": "#6c757d",
}

_CSS = """
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f9fa; color: #212529; }
.container { max-width: 1200px; margin: 0 auto; padding: 24px; }
h1 { font-size: 2rem; margin-bottom: 8px; }
h2 { font-size: 1.4rem; margin: 24px 0 12px; border-bottom: 2px solid #dee2e6; padding-bottom: 6px; }
h3 { font-size: 1.1rem; margin-bottom: 8px; }
.meta { color: #6c757d; font-size: 0.9rem; margin-bottom: 24px; }
.stat-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(120px, 1fr)); gap: 12px; margin-bottom: 24px; }
.stat-card { background: #fff; border-radius: 8px; padding: 16px; text-align: center; box-shadow: 0 1px 3px rgba(0,0,0,.1); }
.stat-card .count { font-size: 2rem; font-weight: 700; }
.stat-card .label { font-size: 0.8rem; color: #6c757d; text-transform: uppercase; }
.badge { display: inline-block; padding: 3px 10px; border-radius: 4px; font-size: 0.78rem; font-weight: 600; color: #fff; }
.vuln-card { background: #fff; border-radius: 8px; margin-bottom: 16px; box-shadow: 0 1px 3px rgba(0,0,0,.1); overflow: hidden; }
.vuln-header { padding: 16px 20px; display: flex; align-items: center; gap: 12px; border-left: 5px solid #dee2e6; }
.vuln-body { padding: 16px 20px; border-top: 1px solid #f0f0f0; }
.vuln-body table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 0.9rem; }
.vuln-body td { padding: 6px 10px; vertical-align: top; border-bottom: 1px solid #f0f0f0; }
.vuln-body td:first-child { font-weight: 600; width: 160px; color: #495057; }
pre { background: #1e1e1e; color: #d4d4d4; padding: 12px; border-radius: 6px; overflow-x: auto; font-size: 0.82rem; margin: 6px 0; }
details > summary { cursor: pointer; font-weight: 600; padding: 8px 0; color: #495057; }
details[open] > summary { color: #212529; }
.steps { list-style: none; }
.steps li { padding: 4px 0 4px 16px; position: relative; }
.steps li::before { content: "→"; position: absolute; left: 0; color: #6c757d; }
.risk-score { font-size: 1.8rem; font-weight: 700; color: #dc3545; }
footer { margin-top: 40px; text-align: center; color: #6c757d; font-size: 0.85rem; padding: 20px; }
</style>
"""


class HTMLReporter:
    """Generates a self-contained HTML vulnerability report."""

    def generate(self, report: VulnerabilityReport, output_path: str) -> str:
        """
        Write the HTML report to *output_path*.

        Returns the path written.
        """
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        html = self._render(report)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return output_path

    def _render(self, report: VulnerabilityReport) -> str:
        meta = report.metadata
        stats = report.summary_stats

        return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Vulnerability Report — {meta.target_url}</title>
{_CSS}
</head>
<body>
<div class="container">

<h1>Vulnerability Report</h1>
<div class="meta">
  Target: <strong>{meta.target_url}</strong> &nbsp;|&nbsp;
  Scan started: {meta.scan_start.strftime('%Y-%m-%d %H:%M UTC')} &nbsp;|&nbsp;
  Duration: {meta.duration_seconds:.0f}s &nbsp;|&nbsp;
  Agents: {', '.join(meta.agents_used)} &nbsp;|&nbsp;
  LLM: {meta.llm_model} &nbsp;|&nbsp;
  Requests: {meta.total_requests}
</div>

{self._render_executive_summary(report)}
{self._render_findings(report)}
{self._render_endpoint_coverage(report)}

<footer>Generated by VulnScanner on {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}</footer>
</div>
</body>
</html>"""

    def _render_executive_summary(self, report: VulnerabilityReport) -> str:
        stats = report.summary_stats
        cards = ""
        for sev in ("CRITICAL", "HIGH", "MEDIUM", "LOW", "INFO"):
            count = stats.get(sev, 0)
            color = _COLORS[sev]
            cards += f"""
<div class="stat-card">
  <div class="count" style="color:{color}">{count}</div>
  <div class="label">{sev}</div>
</div>"""

        return f"""
<h2>Executive Summary</h2>
<div class="stat-grid">
{cards}
<div class="stat-card">
  <div class="count risk-score">{report.risk_score}</div>
  <div class="label">Risk Score</div>
</div>
</div>
<p>
  <strong>{stats.get('TOTAL', 0)}</strong> vulnerabilities found across
  <strong>{report.metadata.endpoints_tested}</strong> endpoints tested.
</p>
"""

    def _render_findings(self, report: VulnerabilityReport) -> str:
        if not report.vulnerabilities:
            return "<h2>Findings</h2><p>No vulnerabilities found.</p>"

        # Sort by severity score desc
        sorted_vulns = sorted(report.vulnerabilities, key=lambda v: v.severity_score, reverse=True)

        cards = ""
        for vuln in sorted_vulns:
            color = _COLORS.get(vuln.severity.value, "#6c757d")
            evidence = vuln.evidence

            req_body = ""
            if evidence.request_body:
                req_body = f"<pre>{_escape(json.dumps(evidence.request_body, indent=2, default=str))}</pre>"

            resp_body = ""
            if evidence.response_body:
                body_str = json.dumps(evidence.response_body, indent=2, default=str) if isinstance(evidence.response_body, (dict, list)) else str(evidence.response_body)
                resp_body = f"<pre>{_escape(body_str[:2000])}</pre>"

            steps_html = "".join(f"<li>{_escape(s)}</li>" for s in vuln.reproduction_steps)

            compare_html = ""
            if evidence.comparison_request_url:
                compare_body_str = json.dumps(evidence.comparison_response_body, indent=2, default=str) if isinstance(evidence.comparison_response_body, (dict, list)) else str(evidence.comparison_response_body or "")
                compare_html = f"""
<tr><td>Owner Response</td><td>
  <code>GET {_escape(evidence.comparison_request_url)}</code> → HTTP {evidence.comparison_response_status}
  <pre>{_escape(compare_body_str[:1000])}</pre>
</td></tr>"""

            cards += f"""
<div class="vuln-card">
  <div class="vuln-header" style="border-left-color:{color}">
    <span class="badge" style="background:{color}">{vuln.severity.value}</span>
    <strong>{_escape(vuln.title)}</strong>
    <span style="margin-left:auto;color:#6c757d;font-size:0.85rem">{vuln.type.value} | {vuln.method} {_escape(vuln.endpoint)}</span>
  </div>
  <div class="vuln-body">
    <table>
      <tr><td>Description</td><td>{_escape(vuln.description)}</td></tr>
      <tr><td>Agent</td><td>{vuln.agent_name}</td></tr>
      <tr><td>Confidence</td><td>{vuln.confidence:.0%}</td></tr>
      {f'<tr><td>CWE</td><td>{vuln.cwe_id}</td></tr>' if vuln.cwe_id else ''}
      <tr><td>Impact</td><td>{_escape(vuln.impact)}</td></tr>
      <tr><td>Remediation</td><td>{_escape(vuln.remediation)}</td></tr>
    </table>

    <details>
      <summary>Reproduction Steps</summary>
      <ul class="steps" style="margin-top:8px">{steps_html}</ul>
    </details>

    <details>
      <summary>Evidence</summary>
      <table style="margin-top:8px">
        <tr><td>Request</td><td><code>{vuln.method} {_escape(evidence.request_url)}</code>{req_body}</td></tr>
        <tr><td>Response</td><td>HTTP {evidence.response_status}{resp_body}</td></tr>
        {compare_html}
        <tr><td>Expected</td><td>{_escape(evidence.expected_behavior)}</td></tr>
        <tr><td>Actual</td><td>{_escape(evidence.actual_behavior)}</td></tr>
      </table>
    </details>
  </div>
</div>"""

        return f"<h2>Findings ({len(sorted_vulns)})</h2>{cards}"

    def _render_endpoint_coverage(self, report: VulnerabilityReport) -> str:
        if not report.metadata.endpoints_tested:
            return ""
        return f"""
<h2>Endpoint Coverage</h2>
<p>{report.metadata.endpoints_tested} endpoints probed during this scan.</p>
"""


def _escape(text: str) -> str:
    """HTML-escape a string."""
    if not isinstance(text, str):
        text = str(text)
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
